apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: personservice-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: personservice
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Pods
    pods:
      metricName: requests_per_second
      targetAverageValue: 60m