apiVersion: v1
kind: Service
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  type: NodePort
  ports:
  - port: 8901
    nodePort: 30002
    protocol: TCP
  selector:
    app: authservice