apiVersion: v1
kind: Service
metadata:
  name: organizationservice
  labels:
    app: organizationservice
spec:
  type: ClusterIP
  ports:
  - port: 8085
    protocol: TCP
  selector:
    app: organizationservice