kind: ConfigMap
apiVersion: v1
metadata:
  name: personservice-dev
data:
  application.yml: |-
    spring:
        profiles: dev
        jpa:
           database: mysql
           hibernate:
            ddl-auto: update
           show-sql: true
           format_sql: true
           generate-ddl: true
           properties:
               hibernate:
                    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
        datasource:
            platform: mysql
            testWhileIdle: true
            validationQuery: SELECT 1
            url: jdbc:mysql://100.120.53.220:3307/personMicroService
            username: ${database-user}
            password: ${database-password}
            
        database:
            driverClassName: com.mysql.jdbc.Driver
        
        redis:
            host: 100.120.53.220
            port: 6379
            
        cloud:    
            stream:
                bindings:
                  input:
                    destination: inboundOrgChanges
                    binder: local_rabbit
                    content-type: application/json
                    group: personservice
                binders:
                  local_rabbit:
                    type: rabbit
                    environment:
                      spring:
                        rabbitmq:
                            host: 100.120.53.220
                            port:  5672
                            username: ${RABBITMQ_SERVICE_USERNAME}
                            password: ${RABBITMQ_SERVICE_PASSWORD}
                            virtual-host: /
            kubernetes:
                ribbon:
                    enabled: true
                    mode: SERVICE 
        zipkin:
            enabled: true
            service:
                name: personservice
            sender:
                type: web
            base-url: http://100.120.53.220:9411
        sleuth:
            enabled: true
            sampler:
                probability: 1.0
    feign:
        hystrix:
            enabled: true
    hystrix:
        circuitBreaker:
            requestVolumeThreshold: 4
            errorThresholdPercentage: 50
            sleepWindowInMilliseconds: 7000
        metrics:
            rollingStats:
                timeInMilliseconds: 15000
                numBuckets: 5
        command:
            default:
                execution:
                    isolation:
                        thread:
                            timeoutInMilliseconds: 21000
            
            OrganizationFeignClient#getOrganization(Integer):
                execution:
                    isolation:
                        thread:
                            timeoutInMilliseconds: 21000
    organizationservice:
        ribbon:
            MaxAutoRetries: 2
            MaxAutoRetriesNextServer: 0
            OkToRetryOnAllOperations: true
            ServerListRefreshInterval: 2000
            ConnectTimeout: 10000
            ReadTimeout: 1000
            KubernetesNamespace: default
            PortName: 8085
            eureka:
                enabled: false
            client:
                enabled: true
    ribbon:
        eager-load:
            enabled: true
            clients: organizationservice
        eureka:
            enabled: false 
        mode: SERVICE        
    management:
        endpoint:
            chaosmonkey:
                enabled: true
            restart:
                enabled: true
        endpoints:
            web:
                exposure:
                    include: "*"
                    
    tracer:
      property: "I AM THE Dev"
    success:
      message: Data saved succesfully in database.