apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: microservice-k8s/auth-server-k8s:1.0
        ports:
        - containerPort: 8901
        env:
        - name: PROFILE
          value: "default" 
        - name: SERVER_PORT
          value: "8901"