apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizationservice
  labels:
    app: organizationservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: organizationservice
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: organizationservice
    spec:
      containers:
      - name: organizationservice
        image: microservice-k8s/organizationmicroservice-k8s:1.0
        volumeMounts:
            - name: secret-db
              mountPath: /etc/secret-db
            - name: secret-rabbitmq
              mountPath: /etc/secret-rabbitmq
        ports:
        - containerPort: 8085
        env:
        - name: PROFILE
          value: "default" 
        - name: SERVER_PORT
          value: "8085"
        - name: ZIPKIN_URI
          value: "http://100.120.53.220:9411"
        - name: SECRET_PATH
          value: "/etc/secret-db,/etc/secret-rabbitmq"  
      volumes:
        - name: secret-db
          secret:
            secretName: mysqldb
          
        - name: secret-rabbitmq
          secret:
            secretName: rabbitmq    